// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Command(arg1) {
  return window['go']['main']['App']['Command'](arg1);
}

export function ExecuteWithInput(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteWithInput'](arg1, arg2, arg3);
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}
